#cloud-config
autoinstall:
  version: 1

  refresh-installer:
   update: true

  keyboard:
    layout: pl

  drivers:
    install: true

  updates: all
  shutdown: poweroff

  ssh:
    install-server: true
    allow-pw: false
    authorized-keys:
      - ${SSH_PUBLIC_KEY}

  packages:
    - git
    - docker.io
    - docker-compose-v2
    - micro
    - curl

  storage:
    layout:
      name: direct

  user-data:
    users:
      - name: ubuntu
        gecos: 'Ubuntu Server Userr'
        sudo: ALL=(ALL) (ALL)
        passwd: '${HASHED_PASSWORD}'
        groups: [adm, dip, lxd, sudo, docker]
        shell: /bin/bash
        lock_passwd: False
    groups:
      - docker

    runcmd:
      - systemctl enable docker.service
      - systemctl start docker.service

    write_files:
      - path: /home/ubuntu/.netrc
        content: |
          machine github.com
          login git
          password ${GITHUB_TOKEN}
        permissions: '0600'
        owner: ubuntu:ubuntu
